---
server:
    install: '1'
    packages: [vim, htop, iotop]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: brexlex, ip: 192.168.50.99, memory: '1024', sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
mysql:
    install: '1'
    root_password: password
    database: db
    user: user
    password: password
    dump: ''
